name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: stable

      - name: Find Flutter project
        id: flutter_project
        run: |
          PROJECT_PATH=$(dirname "$(find . -name pubspec.yaml | head -1)")
          echo "Flutter project found at: $PROJECT_PATH"
          echo "path=$PROJECT_PATH" >> $GITHUB_OUTPUT

      - name: Show files
        run: |
          ls -la
          echo "Project folder:"
          ls -la "${{ steps.flutter_project.outputs.path }}"

      - name: Install packages
        working-directory: ${{ steps.flutter_project.outputs.path }}
        run: flutter pub get

      - name: Build APK
        working-directory: ${{ steps.flutter_project.outputs.path }}
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: ${{ steps.flutter_project.outputs.path }}/build/app/outputs/flutter-apk/app-release.apk
