name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: |
          ls -R

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: stable

      - name: Find Flutter project
        id: flutter_project
        run: |
          PROJECT=$(find . -name pubspec.yaml -exec dirname {} \; | head -n 1)
          echo "PROJECT=$PROJECT" >> $GITHUB_ENV

      - name: Install packages
        working-directory: ${{ env.PROJECT }}
        run: flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT }}
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: ${{ env.PROJECT }}/build/app/outputs/flutter-apk/app-release.apk
